backend:
  name: git-gateway
  branch: main
  auth_endpoint: https://comercialcharito.netlify.app/.netlify/identity

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Precio (S/.)", name: "price", widget: "number", value_type: "float", step: 0.01 }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Categoría", name: "category", widget: "select", 
          options: ["Ropa Mujer", "Ropa Hombre", "Ropa Niños", "Calzado", "Accesorios"] }
      - { label: "Destacado", name: "featured", widget: "boolean", default: false }
