name: Generar index.json de productos

# 1) Permisos: autorizamos push con el GITHUB_TOKEN
permissions:
  contents: write

on:
  push:
    paths:
      - 'productos/**'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      # 2) Checkout con persistencia de credenciales
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 3) Generar index.json
      - name: Generar index.json
        run: |
          cd productos
          echo "Listando archivos en productos/:"
          ls -l
          echo "---"
      
          files=$(ls *.json | grep -v index.json || true)
          echo "Archivos seleccionados para combinar: $files"
      
          if [ -n "$files" ]; then
            jq -s '.' $files > index.json
            echo "✅ index.json creado con contenido de: $files"
          else
            echo "⚠️ No se encontraron archivos JSON para combinar."
          fi

      - name: Mostrar archivos .json detectados
        run: |
          cd productos
          files=$(ls *.json | grep -v index.json || true)
          echo "Archivos detectados: $files"
          if [ -n "$files" ]; then
          jq -s '.' $files > index.json
          echo "index.json regenerado con: $files"
          else
          echo "No se encontraron archivos para combinar."
          fi


      # 4) Commit de index.json si cambió
      - name: Commit index.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add productos/index.json
          git diff --quiet || git commit -m "ci: actualizar productos/index.json"

      # 5) Push a la rama main
      - name: Push cambios
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
