name: Generar index.json de productos

permissions:
  contents: write

on:
  push:
    paths:
      - 'productos/**'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generar index.json
        run: |
          echo "🗂 Listando archivos JSON en productos/:"
          ls -l productos/*.json || echo "No hay archivos"
          
          files=$(ls productos/*.json | grep -v productos/index.json || true)
          echo "🧩 Archivos seleccionados: $files"

          if [ -n "$files" ]; then
            jq -s '.' $files > productos/index.json
            echo "✅ index.json generado"
          else
            echo "⚠️ No se encontraron archivos para combinar"
          fi

      - name: Commit index.json si cambió
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add productos/index.json
          git diff --cached --quiet || git commit -m "ci: actualizar productos/index.json"

      - name: Push a main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
